# SPDX-FileCopyrightText: © 2025 Romain Brault <mail@romainbrault.com>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0
        flags:
          - unit
        paths:
          - "src"
          - "tests"
